### ISSUE TITLE
Typo in plugin.yml

### ISSUE THREAD

**Issue by mibby** [GeorgH93/Bukkit_MarriageMaster#4]
defualt should be default
https://github.com/GeorgH93/Bukkit_MarriageMaster/blob/master/resources/plugin.yml#L114

```
  marry.selfmarry:
    description: Allows to marry an other player without a priest
    defualt: true
  marry.selfdivorce:
    description: Allows to divorce from an other player without a priest
    defualt: true
```
